spring:
  datasource:
    url: jdbc:mariadb://~~~
    driver-class-name: org.mariadb.jdbc.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        ddl-auto: none
    show-sql: false