server:
  port: 8080
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    whitelabel:
      enabled: false

spring:
  profiles:
    default: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB       # TODO: ?? ??
      max-request-size: 215MB   # TODO: ?? ??