server:
  port: 8080
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    whitelabel:
      enabled: false

spring:
  profiles:
    default: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB       # TODO: ?? ??
      max-request-size: 215MB   # TODO: ?? ??

cloud:
  aws:
    credentials:
      access-key: AKIA3WSQMNK5E46XIFP4
      secret-key: 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
    s3:
      bucket: mogayo
    region:
      static: ap-northeast-2
    stack:
      auto: false