spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mogayo
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update