spring:
  datasource:
    url: jdbc:h2:mem:local
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
    show-sql: true